version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:074787506837:task-definition/monew-task:11"
        LoadBalancerInfo:
          ContainerName: monew-app
          ContainerPort: 80