version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:074787506837:task-definition/monew-task:4"
        LoadBalancerInfo:
          ContainerName: monew-app
          ContainerPort: 80
          TargetGroupArn: arn:aws:elasticloadbalancing:ap-northeast-2:074787506837:targetgroup/tg-monew--monew-service/f01b2c192c9d8607