spring:
  application:
    name: monew
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  tomcat:
    threads:
      max: 500
      min-spare: 100
    max-connections: 10000
    accept-count: 10000
  cache:
    type: caffeine
    cache-names: userActivities
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=10m

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  #배치
  batch:
    job:
      enabled: false
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always

article:
  api:
    naver:
      id: ${ARTICLE_API_NAVER_ID}
      secret: ${ARTICLE_API_NAVER_SECRET}
  #article.api.naver.id:test


logging:
  level:
    root: info
    org.springframework.cache: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

log:
  directory: ./logs