spring:
  application:
    name: monew
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  #배치
  batch:
    job:
      enabled: false
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info

