spring:
  application:
    name: monew
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false