name: Java CI with Gradle
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: TEST
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    
    - name: Run Tests Only
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_S3_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_S3_SECRET_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_S3_REGION }}
        AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET }}
        ARTICLE_API_NAVER_ID: ${{ env.ARTICLE_API_NAVER_ID }}
        ARTICLE_API_NAVER_SECRET: ${{ env.ARTICLE_API_NAVER_SECRET }}
      run: ./gradlew test
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ env.CODECOV_TOKEN }}
  
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
      
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
